### ISSUE TITLE
RuntimeError: CUDA error: no kernel image is available for execution on the device

### ISSUE THREAD

**Issue by sshleifer** [microsoft/fastseq#70]
I am trying to use your repeat ngram extension, but when I switch GPUs (without rebuilding the extension) it breaks with `RuntimeError: CUDA error: no kernel image is available for execution on the device`. If I rerun: `python setup.py build_ext --inplace` it works again.  Any clues how to build the extension so that it works on a different GPU (same cuda version, same python version, same torch) than where it was built?

Also, we're considering pulling some of these changes back into `fairseq`, if that's alright with you guys!

**Comment by NickNickGo** [comment]
Hi @sshleifer , 

Could you list the steps to reproduce this error? Also please provide environment info. 

Thanks,

**Comment by sshleifer** [comment]
Hard to explain the cluster setup, but we fixed with ` export TORCH_CUDA_ARCH_LIST="6.0;6.1;7.0"` before building the extension.

Another question, is there an advantage for `NGramRepeatBlock` inheriting from `nn.Module`?

**Comment by yuyan2do** [comment]
@sshleifer We are open to pull some changes back into 'fairseq'. 

> I am trying to use your repeat ngram extension, but when I switch GPUs (without rebuilding the extension) it breaks with `RuntimeError: CUDA error: no kernel image is available for execution on the device`. If I rerun: `python setup.py build_ext --inplace` it works again. Any clues how to build the extension so that it works on a different GPU (same cuda version, same python version, same torch) than where it was built?
> 
> Also, we're considering pulling some of these changes back into `fairseq`, if that's alright with you guys!

**Comment by sshleifer** [comment]
Awesome! If you guys tell me your twitter handles/or some other link I will make sure to credit you when I tweet. The speedup for ngram blocking is really impressive, it will get merged into `fairseq/master` soon.

I'm also trying to prioritize including the other changes:

- `MultiheadAttention`: einsum
-  SequenceGenerator: parallel post-processing
- BeamSearch: ?
- TransformerEncoder, TransformerModel: delete `reorder_encoder_out`


Are the last two changes important? Do you guys have a sense of why?
Is the `MultiheadAttention` just to save memory or also faster?

Thanks and sorry for all the questions.

**Comment by feihugis** [comment]
@sshleifer Thanks for your interest! I think this issue has been resolved. I will close it, but feel free to reopen it if you have more questions.

**Comment by yuyan2do** [comment]
@sshleifer I saw ngram blocking has merged to `fairseq/main`. Do you get chance to try other changes? We have papers ([FastSeq](https://aclanthology.org/2021.acl-demo.26.pdf) and [EL-Attention](http://proceedings.mlr.press/v139/yan21a/yan21a.pdf)) to description the changes now. It may give more sense how it gives speedup.
